#!/usr/bin/env python3
"""Audit estimability selection and exact-zero-flow representation.

This sensitivity analysis is deliberately isolated from completed Stages
01--20. It joins the frozen accepted Stage-15 population, the Stage-17
estimable population, and the exact-zero-flow counts generated by the
tail-direction analysis. It does not refit the variance law and does
not fit or imply a discrete--continuous hurdle model.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import scipy
from scipy import stats


SCRIPT_VERSION = 1
EXPECTED_ACCEPTED = 5227
EXPECTED_ESTIMABLE = 3727
ZERO_STRATA = (
    "none",
    "gt0_lt1_day_per_year",
    "1_lt10_days_per_year",
    "ge10_days_per_year",
)


def parse_args() -> argparse.Namespace:
    project_default = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=project_default)
    parser.add_argument("--output-dir", type=Path, default=None)
    return parser.parse_args()


def clean_gage(values: pd.Series) -> pd.Series:
    """Preserve USGS identifiers as strings, including 8/9/15-digit forms."""
    return values.astype("string").str.strip()


def truthy(values: pd.Series) -> pd.Series:
    return values.astype(str).str.strip().str.lower().isin(("true", "1", "yes"))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_csv(frame: pd.DataFrame, path: Path) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    frame.to_csv(temporary, index=False, float_format="%.12g")
    temporary.replace(path)


def write_json(payload: dict, path: Path) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True, allow_nan=False)
        handle.write("\n")
    temporary.replace(path)


def write_text(text: str, path: Path) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text.rstrip() + "\n", encoding="utf-8")
    temporary.replace(path)


def wilson_interval(successes: int, total: int, confidence: float = 0.95) -> tuple[float, float]:
    if total <= 0:
        return np.nan, np.nan
    z = float(stats.norm.ppf(0.5 + confidence / 2.0))
    p = successes / total
    denominator = 1.0 + z**2 / total
    center = (p + z**2 / (2.0 * total)) / denominator
    half_width = z * np.sqrt(p * (1.0 - p) / total + z**2 / (4.0 * total**2)) / denominator
    return float(center - half_width), float(center + half_width)


def group_count_row(frame: pd.DataFrame, stratifier: str, level: str) -> dict:
    accepted = int(len(frame))
    estimable = int(frame["stage17_primary_estimable"].sum())
    low, high = wilson_interval(estimable, accepted)
    return {
        "stratifier": stratifier,
        "level": str(level),
        "accepted_n": accepted,
        "estimable_n": estimable,
        "nonestimable_n": accepted - estimable,
        "estimability_fraction": estimable / accepted if accepted else np.nan,
        "estimability_wilson95_low": low,
        "estimability_wilson95_high": high,
    }


def continuous_smd(estimable: np.ndarray, nonestimable: np.ndarray) -> float:
    estimable = estimable[np.isfinite(estimable)]
    nonestimable = nonestimable[np.isfinite(nonestimable)]
    if min(len(estimable), len(nonestimable)) < 2:
        return np.nan
    denominator = np.sqrt(
        (np.var(estimable, ddof=1) + np.var(nonestimable, ddof=1)) / 2.0
    )
    return float((np.mean(estimable) - np.mean(nonestimable)) / denominator) if denominator > 0 else np.nan


def binary_smd(p_estimable: float, p_nonestimable: float) -> float:
    denominator = np.sqrt(
        (
            p_estimable * (1.0 - p_estimable)
            + p_nonestimable * (1.0 - p_nonestimable)
        )
        / 2.0
    )
    return float((p_estimable - p_nonestimable) / denominator) if denominator > 0 else np.nan


def distribution_fields(values: Iterable[float], prefix: str) -> dict:
    x = pd.to_numeric(pd.Series(values), errors="coerce").dropna().to_numpy(float)
    if len(x) == 0:
        return {
            f"{prefix}_n": 0,
            f"{prefix}_mean": np.nan,
            f"{prefix}_sd": np.nan,
            f"{prefix}_p25": np.nan,
            f"{prefix}_median": np.nan,
            f"{prefix}_p75": np.nan,
        }
    q25, median, q75 = np.quantile(x, (0.25, 0.50, 0.75))
    return {
        f"{prefix}_n": int(len(x)),
        f"{prefix}_mean": float(np.mean(x)),
        f"{prefix}_sd": float(np.std(x, ddof=1)) if len(x) > 1 else np.nan,
        f"{prefix}_p25": float(q25),
        f"{prefix}_median": float(median),
        f"{prefix}_p75": float(q75),
    }


def assign_zero_stratum(frame: pd.DataFrame) -> pd.Categorical:
    zero_n = pd.to_numeric(frame["q_exact_zero_n"], errors="coerce")
    days_per_year = pd.to_numeric(
        frame["q_exact_zero_days_per_observed_year"], errors="coerce"
    )
    labels = np.select(
        (
            zero_n.eq(0),
            zero_n.gt(0) & days_per_year.lt(1.0),
            days_per_year.ge(1.0) & days_per_year.lt(10.0),
            days_per_year.ge(10.0),
        ),
        ZERO_STRATA,
        default="missing",
    )
    return pd.Categorical(labels, categories=(*ZERO_STRATA, "missing"), ordered=True)


def build_population(
    stage15_path: Path, stage17_path: Path, zero_context_path: Path
) -> tuple[pd.DataFrame, dict]:
    stage15_columns = [
        "GAGE_ID",
        "record_years",
        "q_days",
        "record_span_days",
        "quality_tier",
        "is_reference",
        "AGGECOREGION",
        "aridity",
        "BFI_AVE",
        "log_area",
        "area_km2",
        "FLOW_PCT_EST_VALUES",
        "LAT_GAGE",
        "LNG_GAGE",
        "analysis_population",
    ]
    available = pd.read_csv(stage15_path, nrows=0).columns
    missing_columns = sorted(set(stage15_columns) - set(available))
    if missing_columns:
        raise ValueError(f"Stage 15 lacks required columns: {missing_columns}")
    accepted = pd.read_csv(
        stage15_path,
        usecols=stage15_columns,
        dtype={"GAGE_ID": str},
        low_memory=False,
    )
    accepted["GAGE_ID"] = clean_gage(accepted["GAGE_ID"])
    if accepted["GAGE_ID"].duplicated().any():
        raise ValueError("Stage 15 contains duplicate GAGE_ID values")

    stage17 = pd.read_csv(stage17_path, usecols=["GAGE_ID"], dtype={"GAGE_ID": str})
    stage17["GAGE_ID"] = clean_gage(stage17["GAGE_ID"])
    if stage17["GAGE_ID"].duplicated().any():
        raise ValueError("Stage 17 contains duplicate GAGE_ID values")
    estimable_ids = set(stage17["GAGE_ID"])

    zero_columns = [
        "GAGE_ID",
        "q_observed_n",
        "q_exact_zero_n",
        "q_positive_n",
        "q_negative_n",
        "q_exact_zero_fraction_of_observed",
        "all_transition_touching_exact_zero_n",
        "all_transition_touching_exact_zero_fraction",
        "primary_flagged_transition_n",
        "primary_complete_transition_n",
        "primary_positive_origin_transition_n",
        "primary_nonpositive_origin_transition_n",
        "primary_transition_touching_exact_zero_n",
        "primary_transition_touching_exact_zero_fraction",
        "stage17_primary_estimable",
    ]
    zero_context = pd.read_csv(
        zero_context_path, usecols=zero_columns, dtype={"GAGE_ID": str}
    )
    zero_context["GAGE_ID"] = clean_gage(zero_context["GAGE_ID"])
    if zero_context["GAGE_ID"].duplicated().any():
        raise ValueError("Zero-flow context contains duplicate GAGE_ID values")

    population = accepted.merge(
        zero_context, on="GAGE_ID", how="left", validate="one_to_one", indicator=True
    )
    if not population["_merge"].eq("both").all():
        missing = population.loc[population["_merge"].ne("both"), "GAGE_ID"].tolist()
        raise ValueError(f"Accepted basins missing zero-flow context: {missing[:10]}")
    population = population.drop(columns="_merge")
    provided_estimable = truthy(population.pop("stage17_primary_estimable"))
    population["stage17_primary_estimable"] = population["GAGE_ID"].isin(estimable_ids)
    status_mismatches = int(
        (provided_estimable != population["stage17_primary_estimable"]).sum()
    )
    if status_mismatches:
        raise ValueError(
            f"Zero-flow context and Stage 17 disagree for {status_mismatches} basins"
        )

    population["is_reference"] = truthy(population["is_reference"])
    population["q_exact_zero_days_per_observed_year"] = np.where(
        pd.to_numeric(population["q_observed_n"], errors="coerce").gt(0),
        365.25
        * pd.to_numeric(population["q_exact_zero_n"], errors="coerce")
        / pd.to_numeric(population["q_observed_n"], errors="coerce"),
        np.nan,
    )
    population["observed_discharge_years"] = (
        pd.to_numeric(population["q_observed_n"], errors="coerce") / 365.25
    )
    population["any_exact_zero"] = pd.to_numeric(
        population["q_exact_zero_n"], errors="coerce"
    ).gt(0)
    population["exact_zero_stratum"] = assign_zero_stratum(population)
    population["positive_flow_scope_fraction"] = np.where(
        pd.to_numeric(population["q_observed_n"], errors="coerce").gt(0),
        pd.to_numeric(population["q_positive_n"], errors="coerce")
        / pd.to_numeric(population["q_observed_n"], errors="coerce"),
        np.nan,
    )

    validation = {
        "accepted_basins": int(len(population)),
        "stage17_estimable_basins": int(population["stage17_primary_estimable"].sum()),
        "stage17_nonestimable_basins": int((~population["stage17_primary_estimable"]).sum()),
        "zero_context_status_mismatches": status_mismatches,
        "accepted_ids_absent_from_stage17_or_zero_context": 0,
        "gage_id_length_counts": {
            str(key): int(value)
            for key, value in population["GAGE_ID"].str.len().value_counts().sort_index().items()
        },
    }
    return population, validation


def zero_stratum_summary(population: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for stratum in ZERO_STRATA:
        subset = population.loc[population["exact_zero_stratum"].astype(str).eq(stratum)]
        base = group_count_row(subset, "exact_zero_stratum", stratum)
        rows.append(
            {
                "zero_stratum": stratum,
                **{key: value for key, value in base.items() if key not in ("stratifier", "level")},
                **distribution_fields(
                    subset["q_exact_zero_days_per_observed_year"], "zero_days_per_year"
                ),
                "median_exact_zero_fraction": float(
                    subset["q_exact_zero_fraction_of_observed"].median()
                ),
                "basins_with_primary_zero_touching_transition": int(
                    subset["primary_transition_touching_exact_zero_n"].gt(0).sum()
                ),
                "primary_zero_touching_transition_n": int(
                    subset["primary_transition_touching_exact_zero_n"].sum()
                ),
            }
        )
    return pd.DataFrame(rows)


def continuous_balance(population: pd.DataFrame) -> pd.DataFrame:
    variables = (
        ("record_years", "Stage-15 discharge record length, years"),
        ("observed_discharge_years", "Observed nonmissing discharge days / 365.25"),
        ("aridity", "PET / precipitation aridity index"),
        ("BFI_AVE", "GAGES-II baseflow index, percent"),
        ("log_area", "Natural log basin area"),
    )
    rows = []
    for variable, definition in variables:
        estimable = pd.to_numeric(
            population.loc[population["stage17_primary_estimable"], variable], errors="coerce"
        ).dropna().to_numpy(float)
        nonestimable = pd.to_numeric(
            population.loc[~population["stage17_primary_estimable"], variable], errors="coerce"
        ).dropna().to_numpy(float)
        smd = continuous_smd(estimable, nonestimable)
        rows.append(
            {
                "variable": variable,
                "definition": definition,
                **distribution_fields(estimable, "estimable"),
                **distribution_fields(nonestimable, "nonestimable"),
                "standardized_mean_difference_estimable_minus_nonestimable": smd,
                "absolute_standardized_mean_difference": abs(smd),
                "smd_denominator": "sqrt((SD_estimable^2 + SD_nonestimable^2) / 2)",
            }
        )
    return pd.DataFrame(rows)


def categorical_balance(population: pd.DataFrame) -> pd.DataFrame:
    variables = ("is_reference", "quality_tier", "AGGECOREGION")
    rows = []
    estimable_mask = population["stage17_primary_estimable"]
    for variable in variables:
        levels = sorted(population[variable].dropna().astype(str).unique())
        for level in levels:
            indicator = population[variable].astype(str).eq(level)
            est_n = int(estimable_mask.sum())
            non_n = int((~estimable_mask).sum())
            est_count = int((indicator & estimable_mask).sum())
            non_count = int((indicator & ~estimable_mask).sum())
            est_p = est_count / est_n
            non_p = non_count / non_n
            smd = binary_smd(est_p, non_p)
            rows.append(
                {
                    "variable": variable,
                    "level": level,
                    "estimable_n": est_n,
                    "estimable_level_n": est_count,
                    "estimable_level_fraction": est_p,
                    "nonestimable_n": non_n,
                    "nonestimable_level_n": non_count,
                    "nonestimable_level_fraction": non_p,
                    "standardized_difference_estimable_minus_nonestimable": smd,
                    "absolute_standardized_difference": abs(smd),
                    "smd_denominator": (
                        "sqrt((p_est*(1-p_est) + p_non*(1-p_non)) / 2)"
                    ),
                }
            )
    return pd.DataFrame(rows)


def stratified_counts(population: pd.DataFrame) -> pd.DataFrame:
    rows = [group_count_row(population, "all", "all_accepted")]
    for variable in (
        "exact_zero_stratum",
        "any_exact_zero",
        "quality_tier",
        "is_reference",
        "AGGECOREGION",
    ):
        for level, subset in population.groupby(variable, observed=True, sort=False):
            rows.append(group_count_row(subset, variable, str(level)))
    return pd.DataFrame(rows)


def crossed_zero_counts(population: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for stratifier in ("quality_tier", "is_reference", "AGGECOREGION"):
        for (zero_stratum, level), subset in population.groupby(
            ["exact_zero_stratum", stratifier], observed=True, sort=False
        ):
            row = group_count_row(subset, stratifier, str(level))
            row["zero_stratum"] = str(zero_stratum)
            rows.append(row)
    columns = [
        "zero_stratum",
        "stratifier",
        "level",
        "accepted_n",
        "estimable_n",
        "nonestimable_n",
        "estimability_fraction",
        "estimability_wilson95_low",
        "estimability_wilson95_high",
    ]
    return pd.DataFrame(rows)[columns]


def methods_text() -> str:
    return """# Selection and intermittency sensitivity

This supplementary sensitivity analysis used the 5,227 accepted Stage-15 basins and
identified the 3,727 Stage-17 estimable basins by exact string match to the
frozen Stage-17 diagnostic table. Exact-zero-flow counts came from the
independently receipted tail-direction analysis. No daily records
were reread and no Stage 01--20 result was changed.

For each basin, exact-zero days per observed discharge year were calculated as

`365.25 * q_exact_zero_n / q_observed_n`.

Basins were assigned to four transparent strata: no exact-zero observations;
more than zero but fewer than 1 exact-zero day per observed year; 1 to fewer
than 10 days per year; and at least 10 days per year. Estimability proportions
are accompanied by Wilson 95% intervals.

For continuous attributes, the standardized mean difference is

`(mean_estimable - mean_nonestimable) / sqrt((SD_estimable^2 + SD_nonestimable^2) / 2)`.

For each level of a categorical attribute, the corresponding binary
proportion difference is divided by the square root of the average of the two
Bernoulli variances. These are descriptive balance diagnostics, not causal
effects or hypothesis tests.

The variance estimator requires positive starting flow. Consequently, the
analysis characterizes positive-flow, forcing-screened dry states within
intermittent as well as perennial records. It neither estimates the
probability of entering or leaving zero flow nor constitutes a
discrete--continuous hurdle model. A separate hurdle-state analysis would be
required to make claims about zero-flow occurrence or duration.
"""


def main() -> None:
    args = parse_args()
    root = args.project_root.resolve()
    output_dir = (
        args.output_dir.resolve()
        if args.output_dir is not None
        else root
        / "continental_run"
        / "sensitivity_analyses"
        / "selection_intermittency"
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    stage15_path = (
        root / "continental_run" / "15_continental_results" / "continental_basin_results.csv"
    )
    stage17_path = (
        root
        / "continental_run"
        / "17_distribution_tests"
        / "distribution_basin_diagnostics.csv"
    )
    zero_context_path = (
        root
        / "continental_run"
        / "sensitivity_analyses"
        / "tail_direction"
        / "basin_zero_flow_context.csv"
    )
    inputs = (stage15_path, stage17_path, zero_context_path)
    missing = [str(path) for path in inputs if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Missing required frozen inputs: {missing}")

    population, validation = build_population(
        stage15_path, stage17_path, zero_context_path
    )
    if len(population) != EXPECTED_ACCEPTED:
        raise AssertionError(
            f"Expected {EXPECTED_ACCEPTED} accepted basins; found {len(population)}"
        )
    estimable_n = int(population["stage17_primary_estimable"].sum())
    if estimable_n != EXPECTED_ESTIMABLE:
        raise AssertionError(
            f"Expected {EXPECTED_ESTIMABLE} estimable basins; found {estimable_n}"
        )
    if population["exact_zero_stratum"].astype(str).eq("missing").any():
        raise AssertionError("One or more basins could not be assigned an exact-zero stratum")

    zero_summary = zero_stratum_summary(population)
    continuous = continuous_balance(population)
    categorical = categorical_balance(population)
    counts = stratified_counts(population)
    crossed = crossed_zero_counts(population)

    output_frames = {
        "basin_selection_context.csv": population,
        "zero_flow_stratum_summary.csv": zero_summary,
        "selection_continuous_balance.csv": continuous,
        "selection_categorical_balance.csv": categorical,
        "selection_stratified_counts.csv": counts,
        "zero_flow_cross_strata_counts.csv": crossed,
    }
    outputs: list[Path] = []
    for filename, frame in output_frames.items():
        path = output_dir / filename
        write_csv(frame, path)
        outputs.append(path)

    any_zero = population["any_exact_zero"]
    primary_zero_touch_count = int(
        population["primary_transition_touching_exact_zero_n"].sum()
    )
    summary = {
        "analysis": "selection_and_intermittency_sensitivity",
        "analysis_version": SCRIPT_VERSION,
        "scope": (
            "Descriptive population sensitivity audit using frozen outputs; no "
            "refitting and no discrete-continuous hurdle-model inference."
        ),
        "validation": validation,
        "zero_flow": {
            "basins_with_any_exact_zero": int(any_zero.sum()),
            "fraction_with_any_exact_zero": float(any_zero.mean()),
            "estimable_basins_with_any_exact_zero": int(
                (any_zero & population["stage17_primary_estimable"]).sum()
            ),
            "estimability_fraction_any_exact_zero": float(
                population.loc[any_zero, "stage17_primary_estimable"].mean()
            ),
            "estimability_fraction_no_exact_zero": float(
                population.loc[~any_zero, "stage17_primary_estimable"].mean()
            ),
            "basins_with_any_primary_transition_touching_exact_zero": int(
                population["primary_transition_touching_exact_zero_n"].gt(0).sum()
            ),
            "primary_transitions_touching_exact_zero": primary_zero_touch_count,
            "strata": zero_summary.to_dict(orient="records"),
        },
        "largest_continuous_balance_differences": continuous.nlargest(
            5, "absolute_standardized_mean_difference"
        )[
            [
                "variable",
                "standardized_mean_difference_estimable_minus_nonestimable",
                "absolute_standardized_mean_difference",
            ]
        ].to_dict(orient="records"),
        "interpretation_limits": [
            "Stage-17 estimability is a technical support condition, not a random sample assignment.",
            "Standardized differences are descriptive and do not identify causes of estimability.",
            "The primary estimator conditions on positive starting flow; exact-zero states are outside its continuous variance law.",
            "No hurdle-model parameters or zero-flow transition probabilities are inferred.",
            "Results from basins containing zero-flow days apply only to their retained positive-flow dry-state transitions.",
        ],
    }
    summary_path = output_dir / "analysis_summary.json"
    write_json(summary, summary_path)
    outputs.append(summary_path)
    methods_path = output_dir / "METHODS.md"
    write_text(methods_text(), methods_path)
    outputs.append(methods_path)

    # Independent algebra and count checks before the success receipt is written.
    if int(zero_summary["accepted_n"].sum()) != EXPECTED_ACCEPTED:
        raise AssertionError("Exact-zero strata do not partition the accepted population")
    if int(zero_summary["estimable_n"].sum()) != EXPECTED_ESTIMABLE:
        raise AssertionError("Exact-zero strata do not partition the estimable population")
    if primary_zero_touch_count != 0:
        raise AssertionError(
            "Primary positive-origin transitions unexpectedly touch exact zero"
        )

    receipt = {
        "analysis": "selection_and_intermittency_sensitivity",
        "analysis_version": SCRIPT_VERSION,
        "completed_utc": datetime.now(timezone.utc).isoformat(),
        "project_root": str(root),
        "output_directory": str(output_dir),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "packages": {
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scipy": scipy.__version__,
        },
        "inputs": {str(path.relative_to(root)): sha256_file(path) for path in inputs},
        "code": {
            str(Path(__file__).resolve().relative_to(root)): sha256_file(
                Path(__file__).resolve()
            )
        },
        "outputs": {
            str(path.relative_to(root)): sha256_file(path) for path in outputs
        },
        "metrics": {
            "accepted_basins": EXPECTED_ACCEPTED,
            "estimable_basins": EXPECTED_ESTIMABLE,
            "nonestimable_basins": EXPECTED_ACCEPTED - EXPECTED_ESTIMABLE,
            "basins_with_any_exact_zero": int(any_zero.sum()),
            "exact_zero_strata": len(ZERO_STRATA),
            "primary_transitions_touching_exact_zero": primary_zero_touch_count,
        },
        "upstream_outputs_modified": False,
        "self_checks_passed": True,
    }
    write_json(receipt, output_dir / "_SUCCESS.json")

    print(f"Wrote selection/intermittency audit to {output_dir}")
    print(zero_summary[[
        "zero_stratum", "accepted_n", "estimable_n", "nonestimable_n",
        "estimability_fraction", "estimability_wilson95_low",
        "estimability_wilson95_high",
    ]].to_string(index=False))
    print("\nContinuous estimability balance:")
    print(continuous[[
        "variable", "estimable_mean", "nonestimable_mean",
        "standardized_mean_difference_estimable_minus_nonestimable",
    ]].to_string(index=False))


if __name__ == "__main__":
    main()
